// This file is automatically generated by app.py. Do not edit it manually.
#include "app_params.h"
#include <math.h>

AppParams appParams = {
    .src = {
        .num_channels = 1,
    },
};

void app_params_set_hardware(const HardwareParams *params)
{
    if (params == 0) {
        return;
    }
    appParams.src.hw_ = *params;
}
