// This file is automatically generated by app.py. Do not edit it manually.
#ifndef APP_PARAMS_H
#define APP_PARAMS_H

#include <stdint.h>
#include "hardware_params.h"

#define MIC_BLOCK_SIZE 1280
#define MIC_SAMPLE_RATE 16000
#define MIC_CHANNELS 2
#define MIC_FRAMES_PER_BUFFER 0
#define MIC_SAMPLE_SIZE 16
#define CONFIG_NB_BINS 80
#define VSI0_FILE_PATH "examples/assets/sample_audio.wav"

typedef struct {
    float gain;
} GainParams;

typedef struct {
    HardwareParams hw_;
    int32_t num_channels;
} MicrophoneSourceParams;

typedef struct {
    GainParams gain;
    MicrophoneSourceParams src;
} AppParams;

extern AppParams appParams;
void app_params_set_hardware(const HardwareParams *params);

#endif
