// This file is automatically generated by app.py. Do not edit it manually.
#ifndef APP_PARAMS_H
#define APP_PARAMS_H

#include <stdint.h>
#include "hardware_params.h"

#define APP_BLOCK_SIZE 64
#define APP_MIC_SAMPLE_RATE 16000
#define APP_MIC_CHANNELS 1
#define APP_MIC_FRAMES_PER_BUFFER 0
#define APP_SRC_VALUE 2

typedef struct {
    HardwareParams hw_;
    int32_t num_channels;
} MicrophoneSourceParams;

typedef struct {
    MicrophoneSourceParams src;
} AppParams;

extern AppParams appParams;
void app_params_set_hardware(const HardwareParams *params);

#endif
