// This file is automatically generated by app.py. Do not edit it manually.
#ifndef APP_PARAMS_H
#define APP_PARAMS_H

#include <stdint.h>
#include "hardware_params.h"

#define MIC_BLOCK_SIZE 640
#define MIC_SAMPLE_RATE 16000
#define MIC_CHANNELS 1
#define MIC_FRAMES_PER_BUFFER 0
#define MIC_SAMPLE_SIZE 16
#define VSI0_FILE_PATH "examples/assets/sample_audio.wav"

typedef struct {
    const char * path;
    int32_t delay;
    int32_t num_channels;
    int32_t sample_format;
    int32_t channel_format;
} WavSourceParams;

typedef struct {
    int32_t historyLength;
} KWSClassifyParams;

typedef struct {
    HardwareParams hw_;
} KWSParams;

typedef struct {
    WavSourceParams src;
    KWSClassifyParams classify;
    KWSParams kws;
} AppParams;

extern AppParams appParams;
void app_params_set_hardware(const HardwareParams *params);

#endif
