// This file is automatically generated by app.py. Do not edit it manually.
#pragma once
#include "generic/SlidingBuffer.hpp"
#include "generic/MFCC.hpp"
#include "generic/SlidingBuffer.hpp"
#include "generic/SendToNetwork.hpp"
#include "cmsis/MicrophoneSource.hpp"
#include "generic/Convert.hpp"
#include "generic/KWSClassify.hpp"
#include "generic/KWS.hpp"
