// This file is automatically generated by app.py. Do not edit it manually.
#pragma once
#include "generic/SlidingBuffer.hpp"
#include "generic/CFFT.hpp"
#include "generic/Gain.hpp"
#include "generic/Spectrogram.hpp"
#include "cmsis/MicrophoneSource.hpp"
#include "generic/RealToComplex.hpp"
#include "generic/Convert.hpp"
#include "generic/InterleavedStereoToMono.hpp"
#include "generic/Hanning.hpp"
#include "generic/SpectrogramTextDisplay.hpp"
