# This file is automatically generated by app.py. Do not edit it manually.
set(APP_GENERATED_RUNNER "zephyr")
set(APP_GENERATED_BOARD "fvp_cs300")
set(APP_GENERATED_HARDWARE_TARGET "zephyr/fvp_cs300")
