# This file is automatically generated by app.py. Do not edit it manually.
set(APP_GENERATED_RUNNER "zephyr")
set(APP_GENERATED_BOARD "AlifE7")
set(APP_GENERATED_HARDWARE_TARGET "zephyr/AlifE7")
set(APP_GENERATED_NETWORK "kws_micronet_m_vela_H128.tflite.cpp")
