/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p38-gf512b381
 *
 * Project: 'cmsis_runner.Debug+SSE-300-MPS3' 
 * Target:  'Debug+SSE-300-MPS3' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.25.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55
/* tensorflow::Machine Learning:TensorFlow:Kernel&Ethos-U@1.25.2 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define TF_LITE_DISABLE_X86_NEON 1
        //#define TF_LITE_STRIP_ERROR_STRINGS 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
