// This file is automatically generated by app.py. Do not edit it manually.
#ifndef APP_PARAMS_H
#define APP_PARAMS_H

#include <stdint.h>
#include "hardware_params.h"

typedef struct {
    HardwareParams hw_;
    int32_t value;
} DebugSourceParams;

typedef struct {
    DebugSourceParams src;
} AppParams;

extern AppParams appParams;
void app_params_set_hardware(const HardwareParams *params);

#endif
